Cash Byte App completed
Metaverse-Nabeel/cash-byte pull request #5
Opened 2023-08-11 12:48 UTC by Metaverse-Nabeel

### The following changes have been made to this PR:

**Day 1**

- [ ] Set up the repository and tools.
- [ ] Create your models according to the ERD diagram. Don't forget about validations and tests.
- [ ] Implement the authentication and authorization.

**Day 2**

- [ ] Create the page to add a category.
- [ ] Create the home page.
- [ ] Create the page to add a transaction.
- [ ] Create the transactions page.

**Day 3**

- [ ] Make sure your app is tested adequately.
- [ ] Deploy the project, and test for final details.
- [ ] Record a video for your project.
- [ ] Create a good README and PR description.

**Technical requirements**

- [ ] I used Postgres as your database.
- [ ] I used devise for authentication.
- [ ] I validated all user input to make sure that anyone with bad intentions cannot compromise your app.
- [ ] I used a view template engine of .erb
- [ ] The project can not be deployed and is not accessible online due to some encryption errors I have tried a lot. If you can help me with the deployment then ask for revision otherwise please complete it. I have already taken help from many other developer.

2023-08-11 15:50 UTC, Whoistolu reviewed
Hi @Metaverse-Nabeel 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that its linters are not running. Kindly resolve this. Also, you attached the wrong links for the deployment and the presentation video. Kindly ensure to resolve this as well. Lastly, your MIT link is broken, kindly fix this so your project will be following the proper requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-11 17:00 UTC, Metaverse-Nabeel commented
Hi @Whoistolu,

Thank you so much for your feedback. I have made the required changes. Now, I will again ask for a review.

Regards

2023-08-11 18:18 UTC, NahnahAJ reviewed
## Project Status: INVALIDATED :red_circle: 
Hi @Metaverse-Nabeel , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

- This is because you have submitted a project, that has an error that is preventing me from runnin your app successfully. So kindly fix this :+1: It seems to be coming from your `manifest.js` file :+1: 
- Error message
![image](https://github.com/Metaverse-Nabeel/cash-byte/assets/102699958/a1db7fb5-d8ee-4de0-90b3-c5ab071d97c1)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-11 18:32 UTC, Metaverse-Nabeel commented
Hello @NahnahAJ,

I hope you are doing well. I saw that you have made this PR invalidated but I found everything working perfectly fine. 
 Here is the proof that everything works fine. [Video](https://www.loom.com/share/36d572d20d244bfb941b2fcd33092ce2?sid=9b9e62e8-1500-4f1b-b5c0-f46f1cb49fbd) 
 
Please review it again. 

Thank you

2023-08-11 20:48 UTC, cynthiainga requested changes
Hi @Metaverse-Nabeel, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Use Postgres as the database ✔️ 
- [ ] Descriptive PR ✔️ 

## Required Changes ♻️

- [ ] I left my comment here in my summary because almost all the concerned files are not present in this PR. Kindly make sure to use the correct colors given in the design 🙃 
<img width="339" alt="Screenshot 2023-08-11 at 22 48 56" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/7935b393-8f03-498c-8f79-47076b457cb5">

- [ ] Please kindly make sure your registration page match to the original design 👇🏾 

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="384" alt="Screenshot 2023-08-11 at 22 54 21" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/a64f3a5b-2e23-4e5a-9e16-e4b6c1ce4498"> | <img width="286" alt="Screenshot 2023-08-11 at 22 18 18" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/cc561962-f4ff-4e2e-9524-0c3966ae6628">

- [ ] It would be better to follow the design and make sure the category page match to the original design 'colors,...'

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="384" alt="Screenshot 2023-08-11 at 23 05 23" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/253f19fd-3d15-400a-a8d5-d64deaa7d2eb"> | <img width="382" alt="Screenshot 2023-08-11 at 23 05 47" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/d0f2d829-0854-4b0a-90d2-d3846f019f49">

- [ ] Also kindly make sure that the details page match to the original design (eg: colors, padding, margin,...)

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="378" alt="Screenshot 2023-08-11 at 23 30 27" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/4008ee33-07ac-4351-8005-cc5981843bcd"> | <img width="378" alt="Screenshot 2023-08-11 at 23 31 42" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/3b5d775f-20bb-4e2e-b404-92a95df92231">

- [ ] Please kindly add `confirmable` to your `devise` for the email confirmation, the application should ask for confirmation of email 😁 😁 

- [ ] Kindly check the comments under the review for other changes 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 20:48 UTC, cynthiainga commented on README.md
> +- [Video](https://www.loom.com/share/2f0d707ba4f24105999dff5f9ce26b84?sid=2006c4a2-f8e2-48cf-bba6-f4767db1a198)
- [x] Good job so far but please kindly highlight about a piece of the code that you're proud of as mentioned in the requirement and your video will be completed 🙃 😁 

<img width="1035" alt="Screenshot 2023-08-11 at 22 02 47" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/21654af6-4a3c-4293-8117-b60865ac4492">

- [x] Also the live demo link should be present in the README file, kindly do your best to deploy your project and add the live demo link 🙏🏾 
- [x] The MIT License link is broken kindly fix that, having broken links in the README file doesn’t look more professional 😎 😎 

<img width="1035" alt="Screenshot 2023-08-11 at 22 07 13" src="https://github.com/Metaverse-Nabeel/cash-byte/assets/74501523/a67a8c4d-b021-4e26-b82a-01ea6b45f3a0">

2023-08-11 20:48 UTC, cynthiainga commented on spec/requests/categories_spec.rb
- [ ] Please add tests for this file and the categories in the model folder, you just create the user and category but you didn’t write the tests. Kindly fix that 🙏🏾

2023-08-12 07:23 UTC, fobadara approved these changes
Hi @Metaverse-Nabeel, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![APPRVED](https://user-images.githubusercontent.com/62938735/260206857-3c93f52c-5b21-4f6f-8bc4-be158a13d3cd.gif)
## Highlights
✅ Descriptive README
✅ Descriptive PR summary
✅ Clean code

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-12 07:24 UTC, Metaverse-Nabeel commented
Hello @fobadara 

I hope you are doing well. Thank you so much. I am obliged.

Best Regards

2023-08-12 07:24 UTC, merged